New data collected at 2024-11-18_00-04-01

diff --git a/github-actions/future/test-coverage.yaml b/github-actions/future/test-coverage.yaml
--- a/github-actions/future/test-coverage.yaml
+++ b/github-actions/future/test-coverage.yaml
@@ -1,26 +1,24 @@
-on:
-  push:
-    branches:
-      - main
-  pull_request:
-    branches:
-      - main
+on: [push]
 
 name: test-coverage.yaml
 
 permissions: read-all
 
 jobs:
-
   test-coverage:
-
     runs-on: ubuntu-latest
-
     env:
       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
 
     steps:
       - uses: actions/checkout@v4
+
+      - name: Assert CODECOV_TOKEN is set
+        run: |
+          if [[ -z "${{secrets.CODECOV_TOKEN}}" ]]; then
+            >&2 echo "::error::ERROR: 'secrets.CODECOV_TOKEN' not set"
+            exit 1
+          fi
 
       - uses: r-lib/actions/setup-r@v2
         with:
@@ -31,32 +29,29 @@ jobs:
           extra-packages: any::covr, any::xml2
           needs: coverage
 
+      - name: Install itself
+        run: |
+          install.packages(".", repos = NULL, type = "source")
+        shell: Rscript {0}
+
       - name: Test coverage
         run: |
           cov <- covr::package_coverage(
             quiet = FALSE,
             clean = FALSE,
-            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package"),
-            line_exclusions = list('R/overpass-query.R', 'src/rapidxml.h','src/rapidxml_print.h'),function_exclusions=c('osm_elevation','check_elev_file')
+            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
           )
+          print(cov)
           covr::to_cobertura(cov)
         shell: Rscript {0}
 
       - uses: codecov/codecov-action@v4
         with:
-          # Fail if error if not on PR, or if on PR and token is given
-          fail_ci_if_error: ${{ github.event_name != 'pull_request' || secrets.CODECOV_TOKEN }}
+          fail_ci_if_error: ${{ github.event_name != 'pull_request' && true || false }}
           file: ./cobertura.xml
           plugin: noop
           disable_search: true
           token: ${{ secrets.CODECOV_TOKEN }}
-
-      - name: Show testthat output
-        if: always()
-        run: |
-          ## --------------------------------------------------------------------
-          find '${{ runner.temp }}/package' -name 'testthat.Rout*' -exec cat '{}' \; || true
-        shell: bash
 
       - name: Upload test results
         if: failure()
